version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - ./redisdata:/data
